services:
  php:
    image: 
      php:8.2-apache
    container_name: meu-php
    volumes:
      # macOS
      #- /Volumes/SeagateMacOS/course-PHP/course_php:/var/www/html

      # Linux
      - /media/gilberto-silva/data/course-PHP/course_php:/var/www/html
    ports:
      - "80:80"
      - "443:443"

    links:
      - db

  db:
    image: 
      mysql:latest
    container_name: meu-db
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}   
    ports:
      - "3306:3306"    